version: "3.9"
    
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"

    
#   backend:
#     container_name: backend

# volumes:
#   db_data: {}

